const WA='https://wa.me/256742948759';
const SITE='https://kangarooexpress.vercel.app/';
const SHARE_SITE='https://kangarooexpress.vercel.app/index.html';
const websiteImages={fashion:'assets/category-thumbs-v46/fashion.jpg',electronics:'assets/category-thumbs-v46/electronics.jpg',home:'assets/category-thumbs-v46/home.jpg',furniture:'assets/category-thumbs-v46/furniture.jpg',beauty:'assets/category-thumbs-v46/beauty.jpg',lifestyle:'assets/category-thumbs-v46/home.jpg',sports:'assets/category-thumbs-v46/sports.jpg'};
const cats=[['Fashion & Design','fashion','Bags, footwear & style'],['Electronics','electronics','Smart tech for everyday life'],['Home & Office','home','Useful everyday essentials'],['Furniture','furniture','Comfort meets function'],['Beauty & Care','beauty','Personal care picks'],['Sports & Outdoors','sports','Train, move & explore']];
const products=[
{id:1,name:'1.8L Stainless Steel Electric Kettle',cat:'Home & Office',price:60000,photo:'assets/products/1-8l-stainless-steel-electric-kettle.jpg',tag:'HOT',desc:'Make tea, coffee and hot drinks with ease using this stylish 1.8L stainless steel electric kettle. Designed for fast boiling, it combines a durable stainless-steel body with a heat-resistant handle and convenient safety features for everyday home or office use.',features:['1.8L capacity','1500W power for fast boiling','Stainless steel body','Heat-resistant handle','Auto shut-off for safer boiling','Boil-dry protection','BPA-free and designed for safe everyday use','Suitable for home and office use'],gallery:['assets/products/1-8l-stainless-steel-electric-kettle.jpg']},
{id:2,name:'Hoffmans HM-8841 3L 1800W Electric Food Chopper',cat:'Home & Office',price:80000,photo:'assets/products/hoffmans-hm8841-food-chopper.jpg',tag:'HOT',desc:'Make everyday food preparation faster with the Hoffmans HM-8841 electric food chopper. Its large 3-litre stainless-steel bowl and powerful 1800W motor are designed for chopping and mincing meat, vegetables, fruits, onions and other ingredients with less effort.',features:['3L large-capacity stainless-steel bowl','Powerful 1800W motor','Two-speed operation for different preparation needs','Sharp stainless-steel cutting blades','Suitable for meat, vegetables, fruits, onions and other ingredients','Easy-grip design for convenient handling','Removable bowl and components for easier cleaning','Compact countertop design for everyday home use'],gallery:['assets/products/hoffmans-hm8841-food-chopper.jpg']},
{id:3,name:'Globalstar GS-608 6L 14-in-1 Electric Pressure Cooker',cat:'Home & Office',price:250000,photo:'assets/products/globalstar-gs608-pressure-cooker.jpg',old:285000,tag:'HOT',desc:'Make everyday cooking faster and easier with the Globalstar GS-608 6L electric pressure cooker. Its 14 preset cooking functions, digital controls and automatic pressure and temperature management make it suitable for rice, beans, meat, soup, steaming and other family meals.',features:['6L family-size capacity','1000W power','14 preset cooking menus','Digital control panel with intelligent timer','Automatic pressure and temperature control','Safety lid-lock protection','Removable non-stick inner pot','220–240V, 50/60Hz'],gallery:['assets/products/globalstar-gs608-pressure-cooker.jpg']},
{id:4,name:'Signature Beige Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-hero.jpg',tag:'NEW',desc:'A polished everyday tote with long carry handles, neat leather-look trim and a charming bear detail. Roomy enough for daily essentials while keeping a refined look.'},
{id:5,name:'Chic Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-chic.jpg',tag:'NEW',desc:'A light, fresh tote with aqua-toned handles and a soft structured shape, ideal for everyday shopping, work and casual outings.'},
{id:6,name:'Marble Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-marble.jpg',tag:'NEW',desc:'A stylish marble-pattern tote with a roomy silhouette and coordinated handles, made for practical everyday carrying.'},
{id:7,name:'Elegant Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-elegant.jpg',tag:'NEW',desc:'A soft blush-pink tote with matching handles and a feminine finish, perfect for adding a polished touch to everyday outfits.'},
{id:8,name:'Classic Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-classic.jpg',tag:'POPULAR',desc:'A glossy black classic tote with long handles and a decorative bear charm, combining everyday utility with a bold, timeless finish.'},
{id:9,name:'Premium Shoulder Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-shoulder.jpg',tag:'NEW',desc:'A sleek black shoulder bag with a practical open-top design and useful interior space for everyday essentials.'},
{id:10,name:'Folding Washing Machine',cat:'Home & Office',price:150000,photo:'assets/products/washing-machine.jpg',tag:'HOT',desc:'A compact folding washing machine made for small spaces, travel and convenient everyday laundry.'},
{id:11,name:'ADH Double Door Refrigerator',cat:'Home & Office',price:850000,photo:'assets/products/adh-refrigerator.jpg',tag:'POPULAR',desc:'A spacious double-door refrigerator with separate fridge and freezer sections for organised food storage.'},
{id:12,name:'Skyworth 43” QLED+ Google TV',cat:'Electronics',price:800000,photo:'assets/products/skyworth-43-qled-tv.jpg',old:950000,tag:'SALE',desc:'A 43-inch QLED+ Google TV built for vibrant viewing, smart entertainment and easy connectivity.'},
{id:13,name:'Multi Function Cooking Cooker',cat:'Home & Office',price:470000,photo:'assets/products/multi-function-cooker.jpg',old:520000,tag:'SALE',desc:'A versatile cooker combining gas burners and electric hotplates with an oven for baking, roasting and grilling.'},
{id:14,name:'Black Matte Dinnerware Set',cat:'Home & Office',price:180000,photo:'assets/products/black-matte-dinnerware.jpg',tag:'NEW',desc:'A sleek black matte dining set with bowls, dinner plates and mugs on a metal stand — ideal for everyday dining or gifting.'},
{id:15,name:'Double Tank Deep Fryer',cat:'Home & Office',price:150000,photo:'assets/products/deep-fryer.jpg',tag:'LIMITED',desc:'A stainless-steel double-basket fryer with adjustable temperature control, suitable for home kitchens and small food businesses.'},
{id:16,name:'Hoffmans Electric Kettle / Parcolator',cat:'Home & Office',price:75000,photo:'assets/products/hoffmans-electric-kettle.jpg',tag:'DEAL',desc:'A large-capacity Hoffmans electric kettle with stainless-steel construction, fast boiling and convenient water-level visibility.'},
{id:17,name:'MEWE MW-1108BT Sound Bar',cat:'Electronics',price:200000,photo:'assets/products/mewe-mw-1108bt-soundbar.jpg',tag:'HOT',desc:'A modern MEWE sound bar system with USB, FM, Bluetooth and HDMI ARC connectivity for stronger home entertainment sound.'},
{id:18,name:'MEWE Dry Iron',cat:'Home & Office',price:45000,photo:'assets/products/dry-iron.jpg',tag:'VALUE',desc:'A practical dry iron designed for smooth everyday ironing with a comfortable handle and durable soleplate.'},
{id:19,name:'Ket06BK 5L Electric Kettle',cat:'Home & Office',price:85000,photo:'assets/products/ket06bk-5l-kettle.jpg',tag:'NEW',desc:'A 5-litre electric kettle designed for convenient high-volume boiling at home, in offices or for events.'},
{id:20,name:'BLD03BK 3-in-1 Blender',cat:'Home & Office',price:120000,photo:'assets/products/bld03bk-3in1-blender.jpg',tag:'VALUE',desc:'A 3-in-1 blender set with a large jar and a smaller jar for versatile everyday blending and preparation.'},
{id:21,name:'HSB01BK 2-in-1 Blender 1800W',cat:'Home & Office',price:200000,photo:'assets/products/hsb01bk-2in1-blender.jpg',tag:'POWER',desc:'A powerful 1800W 2-in-1 blender built for fast food preparation, smoothies, sauces and everyday kitchen tasks.'},
{id:22,name:'HSB02BK 2-in-1 Blender 2200W',cat:'Home & Office',price:220000,photo:'assets/products/hsb02bk-2in1-blender.jpg',tag:'POWER',desc:'A high-power 2200W 2-in-1 blender for demanding kitchen use, with strong performance for fast preparation.'},
{id:23,name:'3-Light Solar Kit',cat:'Electronics',price:75000,photo:'assets/products/solar-kit.jpg',tag:'VALUE',desc:'A compact solar lighting kit with three lights, FM, torch, LED lighting and mobile charging support.'},
{id:24,name:'Coffee Tone Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-coffee.jpg',tag:'NEW',desc:'A warm coffee-tone tote with a polished finish and roomy everyday carry space.'},
{id:25,name:'Ocean Blue Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-blue.jpg',tag:'NEW',desc:'A fresh blue tote with a clean silhouette for shopping, work and everyday outings.'},
{id:26,name:'Classic Brown Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-brown.jpg',tag:'POPULAR',desc:'A versatile brown tote with an easy everyday shape and a refined finish.'},
{id:27,name:'Khaki Everyday Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-khaki.jpg',tag:'NEW',desc:'A relaxed khaki tote designed for practical daily carrying with an urban look.'},
{id:28,name:'Beige Everyday Tote Bag',cat:'Fashion & Design',price:55000,photo:'assets/products/bag-beige.jpg',tag:'NEW',desc:'A neutral beige tote with a clean modern look for everyday style.'},
{id:29,name:'0.65L Geepas Capsule Coffee Maker GCM41509 – Red',cat:'Home & Office',price:520000,old:690000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2025/01/30-2.jpg'),tag:'SALE',desc:'Enjoy rich coffee at the touch of a button with this compact 0.65L capsule coffee maker. Its one-touch operation, removable drip tray and compact design make it a convenient choice for home or office use.',features:['0.65L water capacity','Capsule brewing system','One-touch operation','Compact modern design','Fast brewing','Removable drip tray','Energy-efficient automatic shut-off']},
{id:30,name:'3 Lens V380 Pro Solar Camera 4G SIM – Triple Screen PTZ',cat:'Electronics',price:450000,old:579000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2026/02/1004897505.jpg'),tag:'HOT',desc:'Protect your home, shop, farm or compound with a solar-powered 4G security camera featuring three lenses, PTZ control, PIR human detection, night vision and remote monitoring without requiring Wi-Fi.',features:['Triple-lens coverage','4G SIM connectivity','355° pan and up to 90–100° tilt','PIR human detection','Solar panel and rechargeable battery','Two-way audio and siren','Weather-resistant outdoor design','V380 Pro mobile app support']},
{id:31,name:'3m x 3m Cantilever Patio Umbrella – 360° Rotating',cat:'Home & Office',price:1650000,old:2750000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2026/05/1005974580.jpg'),tag:'SALE',desc:'Create a stylish shaded outdoor space with a heavy-duty 3m x 3m cantilever umbrella featuring 360° rotation, tilt adjustment and a water base. Ideal for patios, gardens, restaurants, hotels and poolside spaces.',features:['3m x 3m shade coverage','360° rotating offset design','Tilt adjustment','Heavy-duty construction','Water base','Ideal for patios, gardens, hotels and restaurants']},
{id:32,name:'Afnan 9pm Eau de Parfum for Men – 100ml',cat:'Beauty & Care',price:255000,old:386000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2026/02/1004810034.jpg'),tag:'SALE',desc:'A confident men’s Eau de Parfum with a rich, sweet and modern character, designed for evenings, special occasions and everyday signature style.',features:['Eau de Parfum concentration','Warm sweet character','Designed for evening wear','Elegant presentation','Ideal for gifting']},
{id:33,name:'Camping And Beach Folding Chair – 140kg Capacity',cat:'Sports & Outdoors',price:255000,old:350000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2026/08/1006931042.jpg'),tag:'DEAL',desc:'Relax outdoors with a lightweight folding chair featuring a supportive backrest, spacious seat, side pockets and cup holder. Easy to carry for camping, fishing, beach trips, concerts and park outings.',features:['Up to 140kg capacity','Lightweight foldable design','Supportive backrest','Side pockets','Cup holder','Portable carrying design','Suitable for camping, beach and outdoor events']},
{id:34,name:'IMOU AOV Dual 10MP Solar 360° PTZ Outdoor Security Camera 4G LTE WiFi',cat:'Electronics',price:900000,old:1250000,photo:'/api/product-image?url='+encodeURIComponent('https://nabellasstores.com/wp-content/uploads/2026/07/1006452608.jpg'),tag:'HOT',desc:'Upgrade outdoor security with a dual-lens 10MP solar PTZ camera featuring 360° coverage, 4G LTE and Wi-Fi connectivity, intelligent tracking and vehicle detection for homes, farms and businesses.',features:['Dual-lens 10MP system','360° PTZ coverage','4G LTE and Wi-Fi connectivity','Solar powered operation','Auto tracking','Vehicle detection','Outdoor security design']}
];
if(localStorage.ke_catalog_version!=='partner-v2'){localStorage.removeItem('cart');localStorage.removeItem('wish');localStorage.ke_catalog_version='partner-v2';}
let cart=JSON.parse(localStorage.cart||'[]'),wish=JSON.parse(localStorage.wish||'[]');
try{const cached=JSON.parse(localStorage.ke_partner_catalog||'[]');if(Array.isArray(cached)&&cached.length)cached.forEach(p=>{if(p?.id&&!products.some(x=>x.id==p.id))products.push(p)})}catch(e){}
const money=n=>'UGX '+n.toLocaleString();
const save=()=>{localStorage.cart=JSON.stringify(cart);localStorage.wish=JSON.stringify(wish)};
const get=id=>products.find(p=>p.id==id);
const APP_URL=location.origin+location.pathname;

const seedProducts=products.slice();
let partnerLoadedPages=new Set(), partnerPage=0, partnerTotal=0, partnerLoading=false, partnerDone=false, catalogSyncing=false;
function cleanPartnerText(v){
  return String(v||'').replace(/<a[^>]*href=["'][^"']*["'][^>]*>(.*?)<\/a>/gis,'$1').replace(/<[^>]+>/g,' ').replace(/https?:\/\/[^\s<>]+/gi,'').replace(/www\.[^\s<>]+/gi,'').replace(/nabellas\s*stores/gi,'Kangaroo Express').replace(/nabellasstores\.com/gi,'Kangaroo Express').replace(/info@nabellasstores\.com/gi,'').replace(/\+256\s*785\s*215\s*542/g,'').replace(/\s+/g,' ').trim();
}
function partnerCategory(catsIn=[]){
  const raw=catsIn.map(x=>x.name||'').join(' ').toLowerCase();
  if(/fashion|bag|suitcase|clothing|shoe|wear/.test(raw)) return 'Fashion & Design';
  if(/beauty|health|personal care|groom/.test(raw)) return 'Beauty & Care';
  if(/sport|cycling|outdoor|camping|fitness/.test(raw)) return 'Sports & Outdoors';
  if(/furniture|bed|mattress|wardrobe/.test(raw)) return 'Furniture';
  if(/electronic|camera|phone|tablet|laptop|computer|router|network|printer|tv|audio|speaker|headphone|projector|gaming|smartwatch/.test(raw)) return 'Electronics';
  return 'Home & Office';
}
function normalizePartnerProduct(p){
  const current=Number(p?.prices?.price||0), regular=Number(p?.prices?.regular_price||current);
  const img=p?.images?.[0]?.src||p?.images?.[0]?.thumbnail||'';
  const pid=100000+Number(p.id);
  return {id:pid,sourceId:p.id,name:cleanPartnerText(p.name),cat:partnerCategory(p.categories),price:current,old:regular>current?regular:undefined,photo:img?'/api/product-image?url='+encodeURIComponent(img):'assets/products/placeholder.jpg',tag:regular>current?'SALE':'NEW',desc:cleanPartnerText(p.description||p.short_description),features:(p.attributes||[]).flatMap(a=>(a.terms||[]).map(t=>`${a.name}: ${t.name}`)).slice(0,8),gallery:(p.images||[]).slice(0,6).map(i=>i?.src?'/api/product-image?url='+encodeURIComponent(i.src):'').filter(Boolean),sourceSlug:p.slug};
}
async function loadPartnerPage(page=1){
  if(partnerLoading||partnerLoadedPages.has(page)||partnerDone)return;
  partnerLoading=true;
  try{
    const r=await fetch(`/api/products?page=${page}&per_page=100`,{cache:'no-store'});
    if(!r.ok)throw new Error('Partner catalogue unavailable');
    const data=await r.json();
    const incoming=(data.products||[]).map(normalizePartnerProduct).filter(p=>p.name&&p.price>0);
    const existing=new Set(products.map(p=>String(p.name).toLowerCase()));
    incoming.forEach(p=>{if(!existing.has(p.name.toLowerCase()))products.push(p)});
    try{localStorage.ke_partner_catalog=JSON.stringify(products.filter(x=>x.sourceId||x.id>=100000).slice(-1200))}catch(e){}
    partnerLoadedPages.add(page); partnerPage=Math.max(partnerPage,page); partnerTotal=Number(data.total||partnerTotal); if(page>=Number(data.total_pages||page))partnerDone=true;
    const current=(location.hash.slice(1).split('/')[0]||'home'); if(['home','category','categories','search'].includes(current)) render();
  }catch(e){console.warn(e)}finally{partnerLoading=false}
}
async function loadAllPartnerBatches(){
  await loadPartnerPage(1);
  let pages=Number(partnerTotal?Math.ceil(partnerTotal/100):34);
  for(let page=2;page<=pages;page++){
    await new Promise(r=>setTimeout(r,60));
    await loadPartnerPage(page);
  }
  const current=(location.hash.slice(1).split('/')[0]||'home');
  if(['home','category','categories','search'].includes(current)) render();
}
function startPartnerImport(){loadAllPartnerBatches();}

const link=p=>APP_URL+'#product/'+p.id;
const photo=p=>p.photo;
const imageUrl=p=>String(p.photo||'').startsWith('/api/product-image')?location.origin+p.photo:(/^https?:\/\//i.test(String(p.photo||''))?'/api/product-image?url='+encodeURIComponent(p.photo):SITE+String(p.photo||'').replace(/^\//,''));
const waIcon='<img class="waicon" src="assets/whatsapp.svg" alt="">';
const I={home:'<svg viewBox="0 0 24 24"><path d="M3 10.8 12 3l9 7.8v9.2a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linejoin="round"/></svg>',grid:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.8 8.7c0 5.3-8.8 10.4-8.8 10.4S3.2 14 3.2 8.7A4.7 4.7 0 0 1 12 6.4a4.7 4.7 0 0 1 8.8 2.3Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>',cart:'<svg viewBox="0 0 24 24"><path d="M3 4h2l2 12h10l3-8H6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/><circle cx="9" cy="20" r="1.2"/><circle cx="17" cy="20" r="1.2"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.2" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M5 21c.7-4.2 3-6.2 7-6.2s6.3 2 7 6.2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.7" fill="none" stroke="currentColor" stroke-width="1.9"/><path d="m16 16 5 5" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"/></svg>',menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'};
function go(x){location.hash=x;render();scrollTo(0,0)}
function header(title='',back=false){return `<header><div class="bar"><button class="iconbtn" aria-label="Menu" onclick="${back?"go('home')":"drawer()"}">${back?'‹':I.menu}</button><a class="brand" href="#home"><img src="assets/kangaroo-logo-header.png" alt="Kangaroo Express logo"></a><div class="headtools"><a class="headwa" href="${WA}?text=Hello%20Kangaroo%20Express" aria-label="WhatsApp Kangaroo Express">${waIcon}</a><button class="iconbtn" aria-label="Search" onclick="go('search')">${I.search}</button></div></div>${title?`<div class="pageTitle"><h2>${title}</h2><span>MAKING LIFE EASIER.</span></div>`:`<div class="search" onclick="go('search')">${I.search}<span>Search products, brands & more...</span></div>`}</header>`}
function nav(a='home'){return `<nav>${[['home',I.home,'Home'],['categories',I.grid,'Categories'],['wishlist',I.heart,'Saved'],['cart',I.cart,'Cart'],['account',I.user,'Account']].map(x=>`<button class="${a==x[0]?'on':''}" onclick="go('${x[0]}')"><span class="navicon">${x[1]}</span><small>${x[2]}</small>${x[0]=='cart'&&cart.length?`<em>${cart.reduce((s,x)=>s+x.q,0)}</em>`:''}</button>`).join('')}</nav>`}
function rememberViewed(id){try{let r=JSON.parse(localStorage.ke_recent_viewed||'[]');r=[id,...r.filter(x=>x!=id)].slice(0,10);localStorage.ke_recent_viewed=JSON.stringify(r)}catch(e){}}
function viewedProducts(){try{return JSON.parse(localStorage.ke_recent_viewed||'[]').map(id=>get(id)).filter(Boolean)}catch(e){return[]}}
function card(p){return `<article class="card"><div class="photo"><img loading="lazy" src="${imageUrl(p)}" alt="${p.name}" onclick="go('product/${p.id}')" onerror="this.src='assets/products/placeholder.jpg'"><label>${p.tag}</label><button class="wish" onclick="event.stopPropagation();wishIt(${p.id})" aria-label="Save ${p.name}">${wish.includes(p.id)?'♥':'♡'}</button><button class="quick" onclick="event.stopPropagation();go('product/${p.id}')">Quick view ↗</button></div><section onclick="go('product/${p.id}')"><small>${p.cat}</small><h3>${p.name}</h3><span class="stars">★★★★★ <i>(${20+(Number(p.id)%97)})</i></span><b>${money(p.price)}</b>${p.old?`<del>${money(p.old)}</del><em class="saveBadge">Save ${money(p.old-p.price)}</em>`:''}</section><div class="cardactions"><button class="add" onclick="add(${p.id})"><span>+</span> Add to Cart</button><button class="cardwa" aria-label="Order ${p.name} on WhatsApp" onclick="waOne(${p.id})">${waIcon}<span>Order</span></button></div></article>`}
const slides=[{cat:'all',image:'assets/flyers/hero-deals-rich.jpg',cta:'SHOP DEALS'},{cat:'Electronics',image:'assets/flyers/hero-electronics-rich.jpg',cta:'SHOP ELECTRONICS'},{cat:'Fashion & Design',image:'assets/flyers/hero-fashion-rich.jpg',cta:'SHOP FASHION'},{cat:'Home & Office',image:'assets/flyers/hero-home-rich.jpg',cta:'SHOP HOME'},{cat:'Home & Office',image:'assets/flyers/hero-kitchen-rich.jpg',cta:'SHOP KITCHEN'},{cat:'Electronics',image:'assets/flyers/hero-solar-rich.jpg',cta:'SHOP TECH'}];
const promos=[{image:'assets/flyers_v46/home-new-arrivals.jpg',cat:'all',alt:'Fresh new arrivals'},{image:'assets/flyers_v46/home-kitchen.jpg',cat:'Home & Office',alt:'Kitchen and home essentials'},{image:'assets/flyers_v46/home-tech-deals.jpg',cat:'Electronics',alt:'Technology deals'},{image:'assets/flyers_v46/home-style.jpg',cat:'Fashion & Design',alt:'Style collection'}];
function promoCard(x){return `<button class="promoCard" onclick="go('category/${encodeURIComponent(x.cat)}')"><img src="${x.image}" alt="${x.alt}"></button>`}
function carousel(title,items,action='category/all'){if(!items.length)return '';return `<section class="railSection"><div class="head railHead"><div class="railTitle"><h2>${title}</h2><small class="swipeHint">↔ Swipe</small></div><button onclick="go('${action}')">See all <b>→</b></button></div><div class="productRail">${items.map(card).join('')}</div></section>`}
function dealCountdown(){return `<div class="dealTimer"><span>LIMITED-TIME DEALS</span><b id="dealClock">24:00:00</b><small>Refreshes daily · While stock lasts</small></div>`}
function startDealClock(){clearInterval(window.dealTimer);const key='ke_deal_end';let end=Number(localStorage.getItem(key)||0);if(!end||end<Date.now()){end=Date.now()+24*60*60*1000;localStorage.setItem(key,String(end))}const tick=()=>{const el=document.getElementById('dealClock');if(!el)return;let n=Math.max(0,end-Date.now());let sec=Math.floor(n/1000),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;el.textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')};tick();window.dealTimer=setInterval(tick,1000)}
function home(){const newest=products.filter(p=>p.tag==='NEW').slice(-12).reverse();const deals=products.filter(p=>p.old&&p.old>p.price).sort((a,b)=>(b.old-b.price)-(a.old-a.price)).slice(0,10);const recent=viewedProducts();return header()+`<main><section class="slider" id="slider">${slides.map((s,i)=>`<div class="slide ${i?'':'active'}" role="button" tabindex="0" onclick="go('category/${encodeURIComponent(s.cat)}')" onkeydown="if(event.key==='Enter'||event.key===' ')go('category/${encodeURIComponent(s.cat)}')"><img src="${s.image}" alt="${s.cta}"></div>`).join('')}<div class="sliderdots">${slides.map((_,i)=>`<button onclick="slideTo(${i})" class="${i?'':'on'}"></button>`).join('')}</div></section><div class="quickstrip"><span><i>${I.grid}</i> Curated catalogue</span><span><i>${I.cart}</i> Free Kampala delivery</span><span>${waIcon} Easy WhatsApp ordering</span></div><div class="head"><h2>Shop by Category</h2><button onclick="go('categories')">View all <b>→</b></button></div><div class="cats">${cats.slice(0,6).map(c=>`<button onclick="go('category/${encodeURIComponent(c[0])}')"><img src="${websiteImages[c[1]]}" alt="${c[0]}"><span>${c[0]}</span><small>${c[2]}</small></button>`).join('')}</div><section class="promoGrid">${promos.slice(0,2).map(promoCard).join('')}</section>${catalogSyncing?'<div class="syncSkeleton">Refreshing the catalogue with the latest products…</div>':''}${carousel('New Arrivals',newest)}<section class="dealSection">${dealCountdown()}${carousel('Deals & Savings',deals)}</section>${carousel('Trending Now',products.slice(0,10))}<button class="widePromo" onclick="go('category/all')"><img src="assets/flyers_v46/home-delivery.jpg" alt="Kampala delivery"></button>${recent.length?carousel('Recently Viewed',recent):''}<section class="promoGrid">${promos.slice(2).map(promoCard).join('')}</section>${carousel('Popular Picks',products.slice(10,20))}<section class="trust"><div><span class="trustIcon">${I.grid}</span><b>Curated</b><small>Real products</small></div><div><span class="trustIcon">${I.cart}</span><b>Free</b><small>Kampala delivery</small></div><div><span class="trustIcon">${I.user}</span><b>Support</b><small>Easy ordering</small></div></section></main>${nav()}`}
function categories(){return header('Categories',true)+`<main><div class="catIntro"><span>EXPLORE KANGAROO EXPRESS</span><h1>Shop by category</h1><p>Discover products organised for faster, easier shopping.</p></div><section class="categoriesGrid">${cats.map(c=>`<button class="categoryTile" onclick="go('category/${encodeURIComponent(c[0])}')"><span class="catIcon"><img src="${websiteImages[c[1]]}" alt=""></span><div><b>${c[0]}</b><small>${c[2]}</small></div><em>›</em></button>`).join('')}</section></main>${nav('categories')}`}
function category(name){name=decodeURIComponent(name);let ps=name=='all'?products:products.filter(p=>p.cat==name);const catFlyer={all:'assets/flyers_v46/category-all.jpg','Fashion & Design':'assets/flyers_v46/category-fashion.jpg','Electronics':'assets/flyers_v46/category-electronics.jpg','Home & Office':'assets/flyers_v46/category-home.jpg','Furniture':'assets/flyers_v46/category-furniture.jpg','Beauty & Care':'assets/flyers_v46/category-beauty.jpg','Sports & Outdoors':'assets/flyers_v46/category-sports.jpg'};return header(name=='all'?'All Products':name,true)+`<main><button class="banner bannerImageOnly" onclick="go('category/${encodeURIComponent(name)}')"><img src="${catFlyer[name]||catFlyer.all}" alt="${name} collection"></button><div class="grid">${ps.map(card).join('')||'<div class="empty">No products in this category yet.</div>'}</div></main>${nav('categories')}`}
function product(id){let p=get(id);if(!p)return home();rememberViewed(p.id);const gallery=[p.photo,...(p.gallery||[])].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,6);return header('',true)+`<main><div class="flyer"><div class="flyerImage"><img id="heroProductImage" src="${imageUrl(p)}" alt="${p.name}"></div><div class="flyerInfo"><div class="flyerBrand"><img src="assets/kangaroo-logo-header.png" alt="Kangaroo Express"><span>${p.tag}</span></div><small>${p.cat.toUpperCase()} • KANGAROO EXPRESS</small><h1>${p.name}</h1><div class="flyerPrice">${money(p.price)} ${p.old?`<del>${money(p.old)}</del>`:``}</div><b>FAST KAMPALA DELIVERY • EASY WHATSAPP ORDERING</b></div></div>${gallery.length>1?`<div class="galleryThumbs">${gallery.map((g,i)=>`<button class="${i===0?'on':''}" onclick="selectProductImage('${String(g).replace(/'/g,"\\'")}',this)"><img src="${imageUrl({...p,photo:g})}" alt="View ${i+1}"></button>`).join('')}</div>`:''}<div class="detail"><button class="share" onclick="share(${p.id})">↗ Share</button><label>${p.tag}</label><small class="eyebrow">${p.cat.toUpperCase()}</small><h1>${p.name}</h1><span class="stars">★★★★★ <i>(124 reviews)</i></span><div class="priceRow"><h2>${money(p.price)}</h2>${p.old?`<del>${money(p.old)}</del><span class="saveLarge">Save ${money(p.old-p.price)}</span>`:''}</div><p class="description">${p.desc}</p>${p.features?`<div class="features"><h3>Key Features</h3><ul>${p.features.map(f=>`<li>✓ ${f}</li>`).join('')}</ul></div>`:''}<div class="benefits"><span>✓ Quality checked</span><span>✓ Fast delivery</span><span>✓ WhatsApp support</span></div><div class="detailQty"><span>Quantity</span><button onclick="detailQty(${p.id},-1)">−</button><strong id="dq-${p.id}">1</strong><button onclick="detailQty(${p.id},1)">+</button></div><div class="productactions"><button class="wide" onclick="addQty(${p.id},Number(document.getElementById('dq-${p.id}').textContent)||1)">Add to Cart</button><button class="wa" onclick="waOne(${p.id})">${waIcon} Order on WhatsApp</button></div><div class="linkrow"><a href="${imageUrl(p)}" target="_blank" rel="noopener">↗ Open product image</a><button onclick="copyImage(${p.id})">Copy image link</button></div><div class="miniinfo"><b>Easy ordering</b><span>WhatsApp orders include the product page and image link so our team can identify exactly what you want.</span></div></div><section class="relatedSection">${carousel('You may also like',products.filter(x=>x.id!==p.id&&x.cat===p.cat).slice(0,8),'category/'+encodeURIComponent(p.cat))}</section></main>${nav()}`}
function selectProductImage(src,btn){const img=document.getElementById('heroProductImage');if(img)img.src=imageUrl({photo:src});document.querySelectorAll('.galleryThumbs button').forEach(x=>x.classList.remove('on'));btn?.classList.add('on')}
function add(id){addQty(id,1)} function addQty(id,n){let x=cart.find(x=>x.id==id);x?x.q+=Math.max(1,n):cart.push({id,q:Math.max(1,n)});save();toast('Added to cart')} function detailQty(id,n){const e=document.getElementById('dq-'+id);if(e)e.textContent=Math.max(1,Math.min(99,(Number(e.textContent)||1)+n))}
function wishIt(id){wish.includes(id)?wish=wish.filter(x=>x!=id):wish.push(id);save();render()}
function cartPage(){let total=cart.reduce((s,i)=>s+get(i.id).price*i.q,0);return header('My Cart',true)+`<main>${cart.length?cart.map(i=>{let p=get(i.id);return `<div class="cart"><img src="${imageUrl(p)}"><div><b>${p.name}</b><small>${money(p.price)}</small><div class="qty"><button onclick="change(${p.id},-1)">−</button><strong>${i.q}</strong><button onclick="change(${p.id},1)">+</button></div></div><a class="imglink" href="${imageUrl(p)}" target="_blank" rel="noopener">Image</a><button onclick="removeItem(${p.id})">🗑</button></div>`}).join('')+`<div class="summary">Subtotal <b>${money(total)}</b><br>Delivery <b>FREE</b><small class="freeNote">Within Kampala</small><hr>Total <b>${money(total)}</b><button class="wide" onclick="go('checkout')">Proceed to Checkout →</button><button class="wa" onclick="waCart()">${waIcon} Order on WhatsApp</button><button class="clearcart" onclick="clearCart()">Clear Cart</button></div>`:'<div class="empty">🛒<h2>Your cart is empty</h2><button class="wide" onclick="go(\'home\')">Start Shopping</button></div>'}</main>${nav('cart')}`}
function clearCart(){if(!cart.length)return; if(confirm('Clear all items from your cart?')){cart=[];save();render();toast('Cart cleared')}}
function change(id,n){let x=cart.find(x=>x.id==id);x.q+=n;if(x.q<1)cart=cart.filter(x=>x.id!=id);save();render()}function removeItem(id){cart=cart.filter(x=>x.id!=id);save();render()}
function wishlist(){let ps=products.filter(p=>wish.includes(p.id));return header('My Wishlist',true)+`<main><div class="grid">${ps.map(card).join('')||'<div class="empty">♡<h2>No saved items</h2><button class="wide" onclick="go(\'home\')">Explore Products</button></div>'}</div></main>${nav('wishlist')}`}
function checkout(){return header('Checkout',true)+`<main><div class="steps"><b>1 Delivery</b><span>2 Payment</span><span>3 Review</span></div><div class="form"><h3>Delivery Details</h3><input id="custName" placeholder="Full name" autocomplete="name"><input id="custPhone" placeholder="Phone number" inputmode="tel" autocomplete="tel"><input id="custAddress" placeholder="Kampala, Uganda — delivery address" autocomplete="street-address"><h3>Delivery Option</h3><label><input type="radio" name="delivery" value="Kampala Delivery — FREE" checked> Kampala Delivery <b>FREE</b></label><label><input type="radio" name="delivery" value="Express Delivery — Contact us"> Express Delivery <b>Contact us</b></label><h3>Payment Method</h3><label><input type="radio" name="payment" value="MTN Mobile Money" checked> MTN Mobile Money</label><label><input type="radio" name="payment" value="Airtel Money"> Airtel Money</label><label><input type="radio" name="payment" value="Cash on Delivery"> Cash on Delivery</label><button class="wide" onclick="complete()">Place Order →</button><button class="wa" onclick="waCheckout()">${waIcon} Order via WhatsApp</button></div></main>`}
function checkoutData(){let name=document.getElementById('custName')?.value.trim(),phone=document.getElementById('custPhone')?.value.trim(),address=document.getElementById('custAddress')?.value.trim(),payment=document.querySelector('input[name=payment]:checked')?.value||'Not selected',delivery=document.querySelector('input[name=delivery]:checked')?.value||'Kampala Delivery — FREE';return {name,phone,address,payment,delivery}}
function complete(){waCheckout()}
function makeOrderId(){return 'KE'+Date.now().toString().slice(-8)}
function saveOrder(d){const id=makeOrderId();const items=cart.map(i=>{const p=get(i.id);return {id:p.id,name:p.name,price:p.price,q:i.q,img:imageUrl(p)}});const total=items.reduce((n,x)=>n+x.price*x.q,0);const order={id,created:new Date().toISOString(),status:'Processing',customer:d,items,total};const history=JSON.parse(localStorage.ke_orders||'[]');history.unshift(order);localStorage.ke_orders=JSON.stringify(history.slice(0,30));return order}
function ordersList(){return JSON.parse(localStorage.ke_orders||'[]')}
function trackOrder(id){const o=ordersList().find(x=>x.id===id);const msg=`Hello Kangaroo Express, I would like to TRACK MY ORDER.

Order number: #${id}
Current status shown in my app: ${o?.status||'Processing'}
Customer: ${o?.customer?.name||''}
Phone: ${o?.customer?.phone||''}

Please send me an update on the location/status of my order and expected delivery time. Thank you.`;location.href=WA+'?text='+encodeURIComponent(msg)}
function orderDetails(id){const o=ordersList().find(x=>x.id===id);if(!o)return toast('Order details are unavailable');const items=o.items.map(x=>`<div class="orderItem"><img src="${x.img}" alt=""><div><b>${x.name}</b><small>${x.q} × ${money(x.price)}</small></div></div>`).join('');const el=document.createElement('div');el.className='orderModal';el.innerHTML=`<div class="orderModalShade" onclick="this.parentElement.remove()"></div><section><button class="modalClose" onclick="this.parentElement.parentElement.remove()">×</button><span class="eyebrow">ORDER DETAILS</span><h2>#${o.id}</h2><div class="orderStatus">${o.status}</div><p><b>${o.customer?.name||'Customer'}</b><br>${o.customer?.phone||''}<br>${o.customer?.address||''}</p><div>${items}</div><div class="orderTotal"><span>Total</span><b>${money(o.total)}</b></div><div class="orderModalActions"><button onclick="trackOrder('${o.id}')">${waIcon} Track on WhatsApp</button><button onclick="this.parentElement.parentElement.parentElement.remove()">Continue Shopping</button></div></section>`;document.body.appendChild(el)}
function waCheckout(){let d=checkoutData();if(!d.name||!d.phone||!d.address){alert('Please enter your name, phone number and delivery address first.');return}const order=saveOrder(d);let lines=cart.map(i=>{let p=get(i.id);return `• ${p.name} x${i.q} — ${money(p.price*i.q)}\n  Image: ${imageUrl(p)}`}).join('\n\n');let total=cart.reduce((s,i)=>s+get(i.id).price*i.q,0);let msg=`Hello Kangaroo Express, I want to place an order.\n\nCustomer: ${d.name}\nPhone: ${d.phone}\nAddress: ${d.address}\nDelivery: ${d.delivery}\nPayment: ${d.payment}\n\n${lines}\n\nTOTAL: ${money(total)}\n\nOrder number: #${order.id}

Please confirm my order.`;localStorage.ke_last_order=order.id;cart=[];save();location.href=WA+'?text='+encodeURIComponent(msg)}
function orders(){const os=ordersList();return header('My Orders',true)+`<main><div class="ordersIntro"><span>ORDER HISTORY</span><h1>Your orders</h1><p>View what you ordered and ask our team for a live delivery update.</p></div>${os.length?os.map(o=>`<article class="order"><div class="orderTop"><b>#${o.id}</b><span class="${o.status==='Delivered'?'delivered':'processing'}">${o.status}</span></div><small>${new Date(o.created).toLocaleDateString()} · ${o.items.length} item${o.items.length===1?'':'s'} · ${money(o.total)}</small><div class="orderActions"><button onclick="orderDetails('${o.id}')">View Details</button><button onclick="trackOrder('${o.id}')">${waIcon} Track Order</button></div></article>`).join(''):`<div class="empty">🧾<h2>No orders yet</h2><p>Your completed WhatsApp orders will appear here.</p><button class="wide" onclick="go('home')">Start Shopping</button></div>`}</main>${nav('account')}`}
const AIC={orders:'<svg viewBox="0 0 24 24"><rect x="4" y="3" width="16" height="18" rx="3" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M8 8h8M8 12h8M8 16h5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',saved:'<svg viewBox="0 0 24 24"><path d="M20 21 12 16l-8 5V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>',address:'<svg viewBox="0 0 24 24"><path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="9" r="2.2" fill="none" stroke="currentColor" stroke-width="1.8"/></svg>',payment:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M3 10h18M7 15h4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',help:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M9.8 9a2.3 2.3 0 1 1 4 1.5c-.8.7-1.8 1-1.8 2.2M12 16.5h.01" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',share:'<svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="6" cy="12" r="2.5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="18" cy="19" r="2.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="m8.3 10.9 7.2-4.5M8.3 13.1l7.2 4.5" fill="none" stroke="currentColor" stroke-width="1.8"/></svg>'};
function account(){return header('Account',true)+`<main><div class="accountHero"><div class="accountLogo"><img src="assets/kangaroo-logo-blue-transparent.png" alt="Kangaroo Express"></div><div><span class="eyebrow">KANGAROO EXPRESS</span><h1>Shop smarter. Live easier.</h1><p>Your orders, saved products and shopping preferences — all in one place.</p></div></div><div class="accountStats"><div><b>${cart.reduce((n,x)=>n+x.q,0)}</b><small>Cart items</small></div><div><b>${wish.length}</b><small>Saved items</small></div><div><b>${products.length}+</b><small>Products</small></div></div>${(()=>{const o=ordersList()[0];return o?`<div class="accountLatest"><span class="eyebrow">LATEST ORDER</span><div class="accountLatestTop"><b>#${o.id}</b><b>${o.status}</b></div><p>${o.items.length} item${o.items.length===1?'':'s'} · ${money(o.total)} · ${new Date(o.created).toLocaleDateString()}</p><button onclick="orderDetails('${o.id}')">View order details →</button></div>`:''})()}<div class="menu"><button onclick="go('orders')"><span>${AIC.orders}</span><b>My Orders</b><small>View recent orders</small>›</button><button onclick="go('wishlist')"><span>${AIC.saved}</span><b>Wishlist</b><small>Your saved products</small>›</button><button onclick="toast('Addresses can be added at checkout')"><span>${AIC.address}</span><b>Delivery Addresses</b><small>Manage your delivery details</small>›</button><button onclick="toast('Choose MTN, Airtel or Cash on Delivery at checkout')"><span>${AIC.payment}</span><b>Payment Methods</b><small>MTN • Airtel • Cash on Delivery</small>›</button><button onclick="location.href='${WA}?text=Hello%20Kangaroo%20Express'"><span>${AIC.help}</span><b>Help & Support</b><small>Chat with our team</small>›</button><button onclick="shareApp()"><span>${AIC.share}</span><b>Share Kangaroo Express</b><small>Invite a friend to the live app</small>›</button></div></main>${nav('account')}`}
function search(){return header('Search',true)+`<main><input id="q" class="searchbox" autofocus placeholder="Search products, brands and more..."><div id="res" class="grid">${products.map(card).join('')}</div></main>`}
function drawer(){let d=document.getElementById('drawer');if(d){d.remove();return}d=document.createElement('div');d.id='drawer';d.innerHTML=`<div class="shade" onclick="drawer()"></div><aside><img src="assets/kangaroo-logo-header.png" alt="Kangaroo Express" class="drawerlogo"><h2>Making Life Easier.</h2>${[['home','Home'],['categories','Categories'],['orders','My Orders'],['wishlist','Wishlist'],['cart','Cart'],['account','Account']].map(x=>`<button onclick="drawer();go('${x[0]}')">${x[1]} ›</button>`).join('')}<hr><button onclick="location.href='${WA}?text=Hello%20Kangaroo%20Express'">${waIcon} WhatsApp Support</button></aside>`;document.body.appendChild(d)}
function waOne(id){let p=get(id);rememberViewed(id);let msg=`Hello Kangaroo Express, I want to order:\n\nProduct: ${p.name}\nPrice: ${money(p.price)}\nProduct page: ${link(p)}\nImage link: ${imageUrl(p)}\n\nPlease confirm availability and delivery.`;location.href=WA+'?text='+encodeURIComponent(msg)}
function waCart(){let lines=cart.map(i=>{let p=get(i.id);return `• ${p.name} x${i.q} — ${money(p.price*i.q)}\n  Product page: ${link(p)}\n  Image: ${imageUrl(p)}`}).join('\n\n');let total=cart.reduce((s,i)=>s+get(i.id).price*i.q,0);let msg=`Hello Kangaroo Express, I want to place this order:\n\n${lines}\n\nDelivery: FREE within Kampala\nTOTAL: ${money(total)}\n\nPlease confirm my order and delivery details.`;location.href=WA+'?text='+encodeURIComponent(msg)}
function share(id){let p=get(id),u=link(p);if(navigator.share)navigator.share({title:p.name,text:`${p.name} — ${money(p.price)}`,url:u});else navigator.clipboard?.writeText(u).then(()=>toast('Product link copied'))}
function copyImage(id){navigator.clipboard?.writeText(imageUrl(get(id))).then(()=>toast('Image link copied'))}
function slideTo(i){document.querySelectorAll('.slide').forEach((x,n)=>x.classList.toggle('active',n===i));document.querySelectorAll('.sliderdots button').forEach((x,n)=>x.classList.toggle('on',n===i));window.sliderIndex=i}
function startSlider(){clearInterval(window.sliderTimer);window.sliderIndex=0;window.sliderTimer=setInterval(()=>{if(document.getElementById('slider'))slideTo((window.sliderIndex+1)%slides.length)},4800)}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1400)}

let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;document.documentElement.classList.add('canInstall')});
function shareApp(){const u=SHARE_SITE;if(navigator.share)navigator.share({title:'Kangaroo Express',text:'Shop with Kangaroo Express — Making Life Easier. Open the website to browse the full catalogue.',url:u});else navigator.clipboard?.writeText(u).then(()=>toast('Kangaroo Express website link copied'));}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}location.href='/app/'}

function render(){let [p,a]=location.hash.slice(1).split('/');let h=p||'home';let out=h=='home'?home():h=='categories'?categories():h=='category'?category(a||'all'):h=='product'?product(a):h=='cart'?cartPage():h=='wishlist'?wishlist():h=='checkout'?checkout():h=='orders'?orders():h=='account'?account():h=='search'?search():home();document.getElementById('app').innerHTML=out;let q=document.getElementById('q');if(q){q.oninput=()=>{let s=q.value.toLowerCase().trim();let ps=products.filter(p=>(p.name+' '+p.cat+' '+p.desc).toLowerCase().includes(s));document.getElementById('res').innerHTML=ps.map(card).join('')||'<div class=\"empty\"><h2>No products found</h2><p>Try another product name or category.</p></div>';};}if(h==='home'){startSlider();startDealClock()}}
addEventListener('hashchange',render);
async function boot(){if(!sessionStorage.getItem('ke_splash_seen')){sessionStorage.setItem('ke_splash_seen','1');setTimeout(()=>document.getElementById('splash')?.classList.add('hide'),4000);setTimeout(()=>document.getElementById('splash')?.remove(),4450)}else document.getElementById('splash')?.remove();catalogSyncing=true;render();setTimeout(()=>{if(!localStorage.getItem('ke_update_nudge_v46')){const x=document.createElement('div');x.className='updateNudge';x.innerHTML=`<div><b>Kangaroo Express is freshly updated</b><small>New deals, smarter browsing and a better shopping experience.</small></div><button id="updateNudgeBtn">Got it</button>`;document.body.appendChild(x);document.getElementById('updateNudgeBtn')?.addEventListener('click',()=>{x.remove();localStorage.setItem('ke_update_nudge_v46','1')})}},3500);await startPartnerImport();catalogSyncing=false;render()} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
